# 开发环境配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: framework
    password: framework123
    driver-class-name: oracle.jdbc.OracleDriver
    
    # HikariCP连接池配置
    hikari:
      # 连接池名称
      pool-name: HikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接池大小
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大存活时间（毫秒）
      max-lifetime: 1800000
      # 连接测试查询
      connection-test-query: SELECT 1 FROM DUAL
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
  
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 开发环境打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Apollo配置中心
apollo:
  app-id: ${APOLLO_APP_ID:enterprise-framework}
  meta: ${APOLLO_META:http://localhost:8080}
  # 超时配置
  timeout: 5000  # 5秒超时
  # 连接失败时继续使用本地配置
  cache-dir: ${APOLLO_CACHE_DIR:./config-cache}

# 日志配置
logging:
  level:
    com.guanwei.framework: debug
    org.springframework.security: debug
    com.ctrip.framework.apollo: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"