# 生产环境配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    druid:
      url: ${DB_URL:jdbc:oracle:thin:@prod-oracle:1521:PROD}
      username: ${DB_USERNAME:framework}
      password: ${DB_PASSWORD:framework123}
      
      # 生产环境关闭监控页面
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
  
  # RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_HOST:prod-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:framework}
    password: ${RABBITMQ_PASSWORD:framework123}

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 生产环境关闭SQL打印
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 日志配置
logging:
  level:
    root: warn
    com.enterprise.framework: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/enterprise-framework.log
    max-size: 100MB
    max-history: 30