spring:
  # MongoDB配置（开发环境）
  data:
    mongodb:
      host: 10.56.1.60
      port: 27017
      database: dlzf
      username: caseuser
      password: Guanwei#123
      authentication-database: dlzf
    redis:
      host: 10.56.2.203
      port: 6381
      password: Zhongjj#12_45
      database: 0

  # Oracle数据源配置（202测试环境）
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.56.2.203:1521/orcl
    username: dlzf
    password: Dlzf#12_45

  # Spring配置（202测试环境）
  main:
    allow-bean-definition-overriding: true

  # RabbitMQ配置（202测试环境）
  rabbitmq:
    host: 10.56.2.203
    port: 5672
    username: tlesuser
    password: tles@pass
    virtual-host: /
    connection-timeout: 30000
    requested-heartbeat: 60
    channel-rpc-timeout: 10000
    channel-checkout-timeout: 0
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      receive-timeout: 5000
      reply-timeout: 5000
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
          multiplier: 1.0
          max-interval: 10000
        default-requeue-rejected: false
        idle-event-interval: 60000
        consumer-batch-enabled: false
        batch-size: 1
        batch-buffer-limit: 100
        batch-timeout: 1000

# 日志配置（开发环境）
logging:
  level:
    com.guanwei.tles.casetransfer: DEBUG
    com.guanwei.framework: INFO
    org.springframework.web: INFO
    org.mybatis: INFO
    org.springframework.amqp: INFO
    com.rabbitmq: INFO

cap:
  message-queue:
    type: "rabbitmq"
    rabbitmq:
      # 指定要绑定的交换机名称
      exchange-name: "tles.case-biz.case-v1"
      exchange-type: "topic"
      queue-prefix: "cap_"