server:
  port: 8083
  servlet:
    context-path: /case-transfer

spring:
  application:
    name: guanwei-tles-case-transfer
  profiles:
    active: test

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.guanwei.tles.casetransfer.entity.oracle
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

# CAP消息配置
cap:
  enabled: true
  default-group: "case-transfer-group"
  version: "v1"
  
  # 消息存储配置
  storage:
    type: "oracle"  # 使用Oracle存储
    database:
      connection-string: "${spring.datasource.url}"
      username: "${spring.datasource.username}"
      password: "${spring.datasource.password}"
      schema: "CAP"
      table-prefix: "CAP_"
  
  # 消息队列配置
  message-queue:
    type: "rabbitmq"
    rabbitmq:
      # 指定要绑定的交换机名称
      exchange-name: "tles.case-biz.case-v1"
      exchange-type: "topic"
      queue-prefix: "cap_"
    # 注意：CAP框架会自动创建和管理所有必要的交换机和队列
    # 连接配置继承自spring.rabbitmq，无需重复配置
  
  # 消费者配置
  consumer-thread-count: 10
  enable-subscriber-parallel-execute: true
  subscriber-parallel-execute-thread-count: 5
  subscriber-parallel-execute-buffer-factor: 1
  
  # 发布者配置
  enable-publish-parallel-send: true
  
  # 消息过期配置
  succeed-message-expired-after: 86400  # 成功消息24小时后过期
  failed-message-expired-after: 259200  # 失败消息3天后过期
  
  # 重试配置
  failed-retry-interval: 60  # 失败重试间隔60秒
  failed-retry-count: 3      # 最大重试次数3次
  
  # 清理配置
  collector-cleaning-interval: 3600  # 清理间隔1小时
  scheduler-batch-size: 100          # 调度批处理大小
  
  # 分布式锁配置
  use-storage-lock: true
  
  # 回退窗口配置
  fallback-window-lookback-seconds: 300

# 日志配置
logging:
  level:
    com.guanwei.tles.casetransfer: DEBUG
    com.guanwei.framework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/case-transfer.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
