# CAP消息配置 - 案件传输服务专用
cap:
  enabled: true
  default-group: "case-transfer-group"
  version: "v1"
  
  # 消息存储配置 - Oracle
  storage:
    type: "oracle"
    database:
      connection-string: "${spring.datasource.url}"
      username: "${spring.datasource.username}"
      password: "${spring.datasource.password}"
      schema: "${ORACLE_SCHEMA:CAP}"
      table-prefix: "CAP_"
  
  # 消息队列配置 - RabbitMQ
  message-queue:
    type: "rabbitmq"
    rabbitmq:
      host: "${spring.rabbitmq.host}"
      port: "${spring.rabbitmq.port}"
      username: "${spring.rabbitmq.username}"
      password: "${spring.rabbitmq.password}"
      virtual-host: "${spring.rabbitmq.virtual-host}"
      exchange-name: "tles.case-biz.case-v1"
      exchange-type: "topic"
      queue-prefix: "cap_"
      routing-key: "case.transfer.#"
  
  # 消费者配置
  consumer-thread-count: 10
  enable-subscriber-parallel-execute: true
  subscriber-parallel-execute-thread-count: 5
  subscriber-parallel-execute-buffer-factor: 1
  
  # 发布者配置
  enable-publish-parallel-send: true
  
  # 消息过期配置
  succeed-message-expired-after: 86400  # 成功消息24小时后过期
  failed-message-expired-after: 259200  # 失败消息3天后过期
  
  # 重试配置
  failed-retry-interval: 60  # 失败重试间隔60秒
  failed-retry-count: 3      # 最大重试次数3次
  
  # 清理配置
  collector-cleaning-interval: 3600  # 清理间隔1小时
  scheduler-batch-size: 100          # 调度批处理大小
  
  # 分布式锁配置
  use-storage-lock: true
  
  # 回退窗口配置
  fallback-window-lookback-seconds: 300

# CAP相关日志配置
logging:
  level:
    com.guanwei.framework.cap: DEBUG
    com.guanwei.tles.casetransfer.handler: DEBUG
    org.springframework.amqp: INFO
    com.rabbitmq: INFO 