spring:
  # MongoDB配置（生产环境）- 暂时禁用
  # data:
  #   mongodb:
  #     host: ${MONGODB_HOST:localhost}
  #     port: ${MONGODB_PORT:27017}
  #     database: ${MONGODB_DATABASE:tles_case_db}
  #     username: ${MONGODB_USERNAME:admin}
  #     password: ${MONGODB_PASSWORD:admin123}
  #     authentication-database: admin

  # 禁用MongoDB自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  # Oracle数据源配置（生产环境）
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_URL:jdbc:oracle:thin:@localhost:1521:ORCL}
    username: ${ORACLE_USERNAME:tles_user}
    password: ${ORACLE_PASSWORD:tles_pass}

# CAP配置继承自application-cap.yml
# 生产环境特定配置覆盖
cap:
  # 生产环境优化配置
  consumer-thread-count: 20
  subscriber-parallel-execute-thread-count: 10
  subscriber-parallel-execute-buffer-factor: 2
  failed-retry-count: 5
  scheduler-batch-size: 200

# 日志配置（生产环境）
logging:
  level:
    com.guanwei.tles.casetransfer: INFO
    com.guanwei.framework: WARN
    org.springframework.web: WARN
    org.mybatis: WARN
