server:
  port: 8081
  servlet:
    context-path: /business
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: business-system-example
  
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${ORACLE_USERNAME:business}
    password: ${ORACLE_PASSWORD:business123}
    driver-class-name: oracle.jdbc.OracleDriver
    
    # HikariCP连接池配置
    hikari:
      pool-name: BusinessHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 1
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

# Apollo配置中心
apollo:
  app-id: ${APOLLO_APP_ID:business-system-example}
  meta: ${APOLLO_META:http://localhost:8080}
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,database,redis,rabbitmq

# 日志配置
logging:
  level:
    com.enterprise.business: debug
    com.enterprise.framework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n" 